### ISSUE TITLE
Feature: Initial CloudResume website

### ISSUE THREAD

**Issue by cpalte** [cpalte/CloudResume#3]
# Epic Title

Feature: Initial CloudResume website

## Epic Description

For the Cloud Resume Challenge, a first version with a basic layout of the webpage is uploaded to S3 in AWS.

## List of Tasks (Complete in order)

1. [x] [Task 1: Add Github Templates](https://github.com/cpalte/CloudResume/issues/2)
2. [x] [Task 2: set up website](https://github.com/cpalte/CloudResume/issues/4)
3. [x] [Task 3: Add Visitor Counter](https://github.com/cpalte/CloudResume/issues/6)
